import Navbar from "@/components/Navbar";
import "./globals.css";
import { Rubik } from "next/font/google";

const rubik = Rubik({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Tareas - NextCrud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="shortcut icon"
          href="https://cdn2.iconfinder.com/data/icons/team-and-office/160/Task-64.png"
          type="image/x-icon"
        />
      </head>
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
